### ISSUE TITLE
Forecast from forecast.io isn't accurate

### ISSUE THREAD

**Issue by hrrmsn** [hrrmsn/weather-project#7]
Use foreca.com weather api instead.
http://corporate.foreca.com/en/products-services/data/weather-api

**Comment by hrrmsn** [comment]
Foreca weather api is free only for 1000 first requests.
) :

**Comment by hrrmsn** [comment]
After some researching i decided stay with [forecast.io](https://forecast.io). All free forecast web-services aren't quite accurate. [Forecast.io](https://forecast.io) provides a lot of different weather data.

**Comment by kuelye** [comment]
Dratuti.
